### ISSUE TITLE
Windows npm build issues

### ISSUE THREAD

**Issue by jobokai** [PurdueMarketingAndMedia/purdueTemplates-2015#104]
You may want to edit the ReadMe to include instructions for windows users to use: https://www.npmjs.com/package/win-node-env

NODE_ENV on windows doesn't work like it does on mac. Using the NPM package above made everything work when running the scripts.

**Comment by jyoung295** [comment]
Thanks for catching this! We hadn't even thought about it because the windows laptop we had been testing on had no problem running the scripts for some reason, but it may have been set up in the past to have something like that package installed globally.

I've added the package to our repo and tested on brand new windows hardware and it worked, so it will be coming in the next hotfix which should be before the end of the week.
