### ISSUE TITLE
Goldbar JS and Google Custom Search Engine dependency

### ISSUE THREAD

**Issue by galvarez421** [PurdueMarketingAndMedia/purdueTemplates-2015#4]
Hi,

In https://github.com/PurdueMarketingAndMedia/purdueTemplates-2015/blob/master/components/html/modules/header/_goldBar.html, the search bar uses Google Custom Search Engine.

Out of curiosity, why is this used rather than a plain HTML form?

In one website that uses the template, I replaced the html in the search bar list item to be:

```
<form role="search" action="https://www.purdue.edu/purdue/search.html" method="get" class="goldbar-search-form">
    <input type="text" name="q" placeholder="Search Purdue..." class="goldbar-search-input">
    <input type="submit" class="hide">
</form>
```

and it seems to achieve the same result (with custom styles for .goldbar-search-form and .goldbar-search-input). I'm sure I'm probably missing something, but why is the dependency on JS and Google Custom Search Engine needed?

Thanks!

**Comment by jacobvenable** [comment]
I believe that your solution works perfectly fine as well. However, the only hesitation I have is that Google requires their branding when using custom search.

See their [branding page](https://cse.google.com/docs/branding.html) linked on the [control panel page](https://developers.google.com/custom-search/docs/ui). From what I can tell, they do want "Google Search" either next to or watermarked on the search input.

Still, as long as you add their branding in your implementation, I believe it should still be alright.

As for having the JS dependency, I suppose that I don't see this as a problem in the search page's current state. Since our current results page also depends on JS, it could be a bit annoying to start a search only to find out that you need JS to complete the search.

Perhaps you could use the [Custom Search API](https://developers.google.com/custom-search/json-api/v1/overview) to render some results server-side. That way, search could be JS independent for the sake of Progressive Enhancement. Unfortunately, that comes with a price of $5 per 1000 queries per day.

**Comment by galvarez421** [comment]
@jacobvenable Thank you for clarifying all of that!

After reviewing the branding guidelines page and the output from the Google JS (on https://cse.google.com/cse/docs/branding.html, http://www.purdue.edu/, and the Google Custom Search Engine control panel), it seems like it would probably be better to use the Google JS rather than a custom implementation like the one I described in the initial post if only because using the Google JS would seem to ensure adherence to the branding guidelines more reliably than using a custom implementation would. As you mentioned, I could add Google branding to a custom implementation, but a risk of doing that would be that the implementation would possibly not stay up to date with any updates to Google's branding requirements.

Regarding the JS dependency, I should clarify that in my initial post my concern was not necessarily with the additional JS but rather with the additional dependency in general, specifically the multiple HTTP requests that are associated with the inclusion of the Google JS (ultimately, these extra requests don't matter too much I think. I was just trying to optimize performance at the time). Having said that, I think progressive enhancement is great, including delivering functionality without JS whenever it is possible and makes sense to do so, but in this case I think there are at least 2 issues with implementing the search box without JS:

1. As I described above, implementing the search box without using Google JS presents a risk of violating Google's branding requirements.
2. Given the current implementation of the Goldbar, even if the search box were implemented without JS, JS would still be required to display the search box (unless CSS were disabled) given that the search box is contained within a Bootstrap dropdown menu, so there wouldn't be an outward benefit (again, unless CSS were disabled) to progressively enhancing the search box itself unless the dropdown containing the search box were also progressively enhanced to work without JS. This is similar to your point about the current results page also depending on JS.
