### ISSUE TITLE
Update footer heading levels

### ISSUE THREAD

**Issue by jacobvenable** [PurdueMarketingAndMedia/purdueTemplates-2015#74]
Currently, the headings used on each footer column is a `<h4>` tag, which doesn't necessarily fit with the hierarchy of the page. Instead we should do one of the following:

- Update the tags to be `<h2>`
- Add a visibly hidden `<h2>` for the footer section containing something like "Resources" and update the tags for each footer column to be `<h3>`

**Comment by jacobvenable** [comment]
Addressed in #78

**Comment by galvarez421** [comment]
It seems that there are still some h4 instances in the footer as of 1.6.7, e.g., https://github.com/PurdueMarketingAndMedia/purdueTemplates-2015/blob/v1.6.7/components/html/modules/footer/_resources.html#L24 and https://github.com/PurdueMarketingAndMedia/purdueTemplates-2015/blob/v1.6.7/components/html/modules/footer/_resources.html#L41. Just pointing this out in case it was not intentional!

**Comment by jacobvenable** [comment]
Yes, it absolutely was not. We'll get this in the next hotfix and thank you for pointing that out!

**Comment by jacobvenable** [comment]
Issue addressed and merged in #84
