### ISSUE TITLE
Use img instead of object for Purdue logo SVG?

### ISSUE THREAD

**Issue by galvarez421** [PurdueMarketingAndMedia/purdueTemplates-2015#80]
Based on https://svgontheweb.com/#implementation and https://caniuse.com/#feat=svg-img and https://vecta.io/blog/best-way-to-embed-svg/, it seems that using an img element instead of an object element for the Purdue logo SVG in the header might be a good option.

One thing to note from the last article (https://vecta.io/blog/best-way-to-embed-svg/#doubleloading) is that the png fallback image actually gets loaded anyway even if the SVG image loads. I confirmed this behavior in Firefox 60.4.0 ESR and Chrome 71.

**Comment by jacobvenable** [comment]
The reason we decided to use an `<object>` was because it provided an easy way of providing a raster fallback for older browsers that don't support SVG without needing any JS; however, I wasn't aware that it was downloading the raster version whether SVG was supported or not.

That definitely isn't optimal. From briefly researching, there doesn't really seem to be a way to prevent this without JS, and at that point we may as well use something like modernizr for feature detection and use the `<img>` element. Thoughts @jyoung295 ?

**Comment by jyoung295** [comment]
I think it's sort of a matter of preference; `<object>` tags seem to have been the older preferred method, but I don't see any reason why we can't use `<img>` tags instead. We don't need to perform any actions on the svg itself, or we'd already be using inline `<svg>`.

(If we apply this change then we also need to apply it to the other logos, it appears that they double load too.)

**Comment by jacobvenable** [comment]
I suppose we could provide a fallback using onerror:
```html
<img src="your.svg" onerror="this.src='your.png'">
```
I'm not the biggest fan of this solution, since it would require the user to have JS enabled, but I think the audience suffering from double downloads is larger than those using older browsers with JS disabled.

I'm good with implementing this in the next minor update.
