### ISSUE TITLE
Update repo to version 2.0.0 for major breaking changes

### ISSUE THREAD

**Issue by jobokai** [PurdueMarketingAndMedia/purdueTemplates-2015#90]
After hearing the discussion and plans to drop bootstrap and jquery; migrating towards a more customized and slim build. I would propose that the project move to v2.0.0 instead of a minor version update to better reflect the major breaking changes/differences in the builds. While general look and feel styles may not be impacted, the back-end architecture could have major impacts to projects subscribed.

An example would be a project that may not be pulling jquery directly (since it was pulled from the templates) would need to require it specifically if it were removed from the templates. That sort of change should happen from 2.0.0 updates but not 1.8.0 updates.

**Comment by jyoung295** [comment]
This is certainly a good suggestion and makes perfect sense. We (Mike and I) had landed on labeling it as a minor update since our version numbering is publicly facing to clients who don't work directly with any code, so we wanted to make sure not to confuse them with a major version change. We also thought it might be strange to make this a major version then implement *another* major version only a few months later when we do end up updating look and feel.

I suppose rolling it out as a major change does make sense in that context anyway, considering that it's going to be a pretty large change in Cascade too, so technically it affects those clients whether they'll realize it or not. 

Any further thoughts?

**Comment by jobokai** [comment]
I think from a developer standpoint it’d make sense for it to be 2.0.0 then when the visual updates hit then they start as 2.1.0 as they’d be building off the backend setup. In the end though it’s just semantics to better help developers know what they are working with.

**Comment by jyoung295** [comment]
Right I completely agree. We'll tag it as 2.0.0 when it's ready to release. Thanks for the suggestion!
